import random
import time
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

# List of 30 different words to search
words = ["Krish gaming 1455",
         "Krish G 1455",
         "KG1455",
         "denji 1455",
         "Krishgaming 1455",
         "krishgaming1455",
         "krishgaming1455yt",
         "krishgaming145",
         "krishg1455",
         "krishgaming1455 subscriber",
         "ytkrishgaming1455",
         "connector",
         "cable",
         "wire",
         "antenna",
         "transducer",
         "sensor",
         "detector",
         "actuator",
         "controller",
         "processor",
         "memory",
         "denjigaming1455",
         "krishgaming_1455",
         "denji krish gaming 1455",
         "interface",
         "bus",
         "protocol",
         "standard",
         "specification",
         "guideline",
         "policy",
         "procedure",
         "method",
         "technique",
         "approach",
         "strategy",
         "tactic",
         "practice",
         "routine",
         "habit",
         "skill",
         "talent",
         "ability",
         "capacity",
         "competence",
         "performance",
         "potential",
         "achievement",
         "result",
         "outcome",
         "product",
         "service",
         "system",
         "solution",
         "application",
         "tool",
         "resource",
         "facility",
         "equipment",
         "instrument",
         "machine",
         "device",
         "apparatus",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "gadget",
         "gizmo",
         "widget",
         "instrument",
         "utensil",
         "tool",
         "implement",
         "appliance",
         "furniture",
         "fixture",
         "apparatus",
         "equipment",
         "machine",
         "device",
         "apple",
         "banana",
         "cherry",
         "date",
         "fig",
         "grape",
         "kiwi",
         "iphone",
         "samsung galaxy",
         "laptop",
         "television",
         "headphones",
         "camera",
         "watch",
         "tablet",
         "router",
         "printer",
         "projector",
         "game console",
         "smart speaker",
         "fitness tracker",
         "drone",
         "virtual reality",
         "smartwatch",
         "security camera",
         "wireless earbuds",
         "external hard drive",
         "smart thermostat",
         "smart bulb",
         "smart plug",
         "gaming mouse",
         "mechanical keyboard",
         "monitor",
         "webcam",
         "microphone",
         ]

# Shuffle the words list to ensure randomness
random.shuffle(words)

# Initialize the Microsoft Edge web browser
driver_path = "F:\minecraft java\edge-keyword-search-automation-bot-main\msedgedriver.exe"
service = Service(driver_path)
driver = webdriver.Edge(service=service)

try:
    for word in words:
        # Open a new browser window and navigate to Bing
        url = "https://www.bing.com/"  # Replace with the desired URL
        driver.get(url)

        # Find the search input field and enter the word
        search_box = driver.find_element(By.NAME, "q")
        search_box.clear()
        search_box.send_keys(word + Keys.RETURN)

        # Wait for some time before searching the next word
        time_delay = random.randrange(5, 15)
        print(f"Word: {word} || Delay: {time_delay}")
        time.sleep(time_delay)  # Adjust the delay as needed
except KeyboardInterrupt:
    # Close the browser window when the script is stopped
    driver.quit()
